### ISSUE TITLE
arm64 container availability

### ISSUE THREAD

**Issue by t4nki** [academo/grafana-alerting-ntfy-webhook-integration#1]
Hi,

This project would look great in my homelab, unfortunately this is only available for amd64 architecture

Do you have any plans releasing this container on arm64 ?

Ntfy and Grafana both run great on Raspberry Pi ans your project would fit nicely between the two.

I have absolutely no experience regarding Go and coding in general, so I would be of absolutely no help, except for testing

Keep the community posted about this

Regards

**Comment by academo** [comment]
@t4nki you can easily build this for arm64 since go is cross compiling. 

>Keep the community posted about this

where would that be?

**Comment by academo** [comment]
Nevertheless here's a release with all the architecture: https://github.com/academo/grafana-alerting-ntfy-webhook-integration/releases/tag/0.4.1

**Comment by sjafferali** [comment]
I tried using this, but noticed the container is still amd64 only https://hub.docker.com/r/academo/grafana-ntfy/tags . Can a multi arch container also be created for this? I haven't used go-release-action, but the docker [docker/build-push-action](https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54) supports this.

**Comment by academo** [comment]
@sjafferali I release the docker container manually. Considering is a container, can you run it using amd64?

**Comment by sjafferali** [comment]
> @sjafferali I release the docker container manually. Considering is a container, can you run it using amd64?

No, running the amd64 container on an arm64 machine doesn't work. The container exits out immediately with an `exec format error`.

**Comment by academo** [comment]
@sjafferali I see. What I can advice for now is simply to download the binary for the architecture and use an alpine image to run it directly. e.g.:

```yml
version: "3"
services:
  grafana-ntfy:
    #image: arm64v8/alpine
    image: alpine
    # make sure to put the correct architecture binary 
    command: sh -c "/app/grafana-ntfy -ntfy-url 'https://ntfy.sh/mytopic'"
    volumes:
      - ./:/app
    working_dir: /app
    expose:
      - 8080 #only accesible to other containers
```
