### ISSUE TITLE
Error: "flag provided but not defined"

### ISSUE THREAD

**Issue by schenklklopfer** [academo/grafana-alerting-ntfy-webhook-integration#8]
I try to start your tool providing username and password for my selfhosted ntfy instance.
All I get is this error: flag provided but not defined

I tried several things but the error is always the same.
Maybe I just do not understand how to set this settings correctly.

Here the docker-compose.yml parts I use:
```
...
  grafana-ntfy:
    image: academo/grafana-ntfy:latest
    restart: unless-stopped
    expose:
      - 8080 #only accesible to other containers
    networks:
      - metrics
    command:
      - "-username 'grafana' -password 'super-secure-pw' -ntfy-url 'https://selfhosted-ntfy-server.tld/grafana'"
```

The message I get in full term is:
```
flag provided but not defined: -username 'grafana' -password 'super-secure-pw' -ntfy-url 'https://selfhosted-ntfy-server.tld/grafana'
Usage of /usr/local/bin/grafana-ntfy:
  -addr string
    	The address to listen on (default ":8080")
  -allow-insecure
    	Allow insecure connections to ntfy-url
  -debug
    	print extra debug information
  -ntfy-url string
    	The ntfy url including the topic. e.g.: https://ntfy.sh/mytopic
  -password string
    	The ntfy password
  -port int
    	DEPRECATED. Use listenAddr. The port to listen on (default 8080)
  -username string
    	The ntfy username

```

What is wrong here?
